### ISSUE TITLE
letsencrypt dev versions won't install without pip --pre flag

### ISSUE THREAD

**Issue by witten** [thefinn93/ansible-letsencrypt#1]
The dev versions of letsencrypt, the only versions on pypi as of now, won't actually install unless the following is added to the "pip:" line in main.yml:

```
extra_args=--pre
```

This instructs pip to allow installation of pre-release/development versions of packages.

Note, I do have an ancient version of pip (1.5.6), but I suspect this is an issue even in newer versions. If this is not the case, feel free to just tell me to upgrade.

Here's the ansible output before that "fix":

```
TASK: [letsencrypt | Install letsencrypt] ************************************* 
failed: [example.com] => (item=letsencrypt) => {"cmd": "/usr/local/src/letsencrypt/env/bin/pip install -U letsencrypt", "failed": true, "item": "letsencrypt"}
msg: stdout: New python executable in /usr/local/src/letsencrypt/env/bin/python2
Also creating executable in /usr/local/src/letsencrypt/env/bin/python
Installing setuptools, pip...done.
Running virtualenv with interpreter /usr/bin/python2
Downloading/unpacking letsencrypt
  Could not find a version that satisfies the requirement letsencrypt (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104)
Cleaning up...
No distributions matching the version for letsencrypt
Storing debug log for failure in /root/.pip/pip.log

failed: [example.com] => (item=letsencrypt-apache) => {"cmd": "/usr/local/src/letsencrypt/env/bin/pip install -U letsencrypt-apache", "failed": true, "item": "letsencrypt-apache"}
msg: stdout: Downloading/unpacking letsencrypt-apache
  Could not find a version that satisfies the requirement letsencrypt-apache (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104)
Cleaning up...
No distributions matching the version for letsencrypt-apache
Storing debug log for failure in /root/.pip/pip.log

failed: [example.com] => (item=letsencrypt-nginx) => {"cmd": "/usr/local/src/letsencrypt/env/bin/pip install -U letsencrypt-nginx", "failed": true, "item": "letsencrypt-nginx"}
msg: stdout: Downloading/unpacking letsencrypt-nginx
  Could not find a version that satisfies the requirement letsencrypt-nginx (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104, 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151030, 0.0.0.dev20151104)
Cleaning up...
No distributions matching the version for letsencrypt-nginx
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by thefinn93** [comment]
wooo people testing my shit! So, I've tested it and had it work, but that might be some fucked up thing I did to this poor server that I forgot about. Sooooo upgrade pip, if it still doesn't work I'll add the `--pre` thing. Might do that anyway

**Comment by witten** [comment]
The install error does *not* occur in a test virtualenv with pip 7.1.2. Also does not occur with 6.0.8, another common version. And I confirmed it does occur in a test virtualenv with pip 1.5.6.

So maybe just close this wontfix.

**Comment by thefinn93** [comment]
Hrm, does adding `extra_args=--pre` break anything in newer python versions? Might just add that anyway

**Comment by witten** [comment]
It doesn't break anything in newer Python versions, but it could cause a machine to inadvertently install a development / non-production version of the package, if one were to exist on pypi.

**Comment by thefinn93** [comment]
Hrm, that sounds like something that'll come along and bite me in the ass later. I'm not sure if I had done it when you first tested, but for a while now it installs the latest version of pip and setuptools in the virtualenv before installing the Let's Encrypt client, so maybe that'll make everything work without any inadvertent side effects? Any way you can test?

**Comment by witten** [comment]
Confirmed. That results in a Let's Encrypt virtulaenv that contains a modern version of pip (7.1.2).

**Comment by thefinn93** [comment]
Great! Closing this
