### ISSUE TITLE
Issuing via the standalone authenticator leaves incorrect renewal settings

### ISSUE THREAD

**Issue by thefinn93** [thefinn93/ansible-letsencrypt#12]
If we initially use the standalone authenticator before we've started the webserver, it tells the renewer to use the standalone authenticator. I propose we edit the values in `/etc/letsencrypt/renewal/{{ letsencrypt_cert_domain[0] }}.conf` as needed to use the webroot authenticator

**Comment by thefinn93** [comment]
This is being worked on as of 932c503aa2333ff0d9a49f8eff1febf14da1d396 which *appears* to fix it but I want to test more before I merge it to master

**Comment by jcalonso** [comment]
Hello, whats the status of this? I'm trying to renew using the cron, but seems to be using the web server way instead of the webroot challenge.
```
required ports is already taken
```

**Comment by thefinn93** [comment]
Odd. The status of this is it *should* be closed, but based on your report i'm leaving it open. I [merged the renewal branch](https://github.com/thefinn93/ansible-letsencrypt/commit/0fe3e77958725a7c0d68f0bdd4cc6640d7664393) a while ago, which should go and rewrite the renewal file, and it generally works for me. Could you post your renewal file? (`/etc/letsencrypt/renewal/<your domain>.conf`) I think it's generally free of confidential information, but feel free to censor bits of it, just make it obvious what you censored.
