### ISSUE TITLE
letsencrypt doesn't get updated automatically

### ISSUE THREAD

**Issue by thomasrebele** [thefinn93/ansible-letsencrypt#21]
Problem: Recently, letsencrypt has sent me emails that the validity of my certificats will end soon. So I rerun ansible-letsencrypt. I checked the validity with the following command and wondered why the certificate didn't get updated ([source for this command](http://www.shellhacks.com/en/HowTo-Check-SSL-Certificate-Expiration-Date-from-the-Linux-Shell))
    
    echo | openssl s_client -connect www.example.org:443 2>/dev/null | openssl x509 -noout -dates
    
Solution: I discovered that ansible-letsencrypt doesn't update the source code of letsencrypt, so I deleted it and run ansible-letsencrypt again, which fixed my issue :)

    rm -rf /usr/local/share/letsencrypt/
    # run ansible-letsencrypt again

**Comment by thefinn93** [comment]
Oh dear! I thought it was set to auto-update on re-run, but it looks like it isn't. Fixed in 3acf595

**Comment by thefinn93** [comment]
Thanks for the report.
