### ISSUE TITLE
Certificates are not reissued upon letsencrypt_server change

### ISSUE THREAD

**Issue by vialcollet** [thefinn93/ansible-letsencrypt#24]
Hi and thanks for this fantastic work!!
It makes it so easy to use let's encrypt :)
I was testing the role and using Let's Encrypt staging server. Then I commented my letsencrypt_server  variable. The role didn't try to re-issue the certificate.
Anything we can do for this?

**Comment by thefinn93** [comment]
That'd be pretty tricky to do. It decides to run the issuance command based on whether or not a cert for that name exists. I'd say if you want to switch servers, rm or mv the certs between. I wouldn't want this role to automatically delete certs for any reason.
