### ISSUE TITLE
Make this an ansible  galaxy role?

### ISSUE THREAD

**Issue by thermistor** [thefinn93/ansible-letsencrypt#28]
Is there a reason you don't have this on galaxy? I prefer to use galaxy roles when I can.

**Comment by thefinn93** [comment]
Oh that was pretty simple. I clicked a button on the website and now it's magically [here](https://galaxy.ansible.com/thefinn93/letsencrypt) I think? Please confirm and close if it worked

**Comment by hedii** [comment]
i just installed it with ansible galaxy, so it worked :)

**Comment by thermistor** [comment]
Thanks! 
As per #31 it's nice to use versioning so you can push stable releases to galaxy and people can then get the same package every time until they are ready to try an upgrade. It wasn't clear to me at first how it's done, the trick is to use tags with semantic versioning, ie. `git tag -a v0.0.1 -m "Initial version"` and then `git push origin v0.0.1` and then go to galaxy and reimport it.

**Comment by thermistor** [comment]
People can then pin a version in their `requirements.yml` as per [these docs](http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files).
