### ISSUE TITLE
How do I use this? 

### ISSUE THREAD

**Issue by zfrenchee** [thefinn93/ansible-letsencrypt#38]
Hello, 
I'm fairly new to Ansible, and in light of that I was hoping I could ask for a few additions to the README, particularly: 
- What are the steps you need to take to use this ansible role? Should you clone the repo or just copy over the tasks or use the [ansible-galaxy](https://galaxy.ansible.com/thefinn93/letsencrypt/) command? A quick TUTORIAL.md (or a few more steps listed in README.md) would be super helpful.
- How does this role compare to the other dozen or so ansible roles for letsencrypt? I'm starting with this one because it has more stars and seems like it's under more active development. Are they all mostly the same, or do they do different things? 

Thanks!

**Comment by zfrenchee** [comment]
A slightly more specific question to my use case: If I wanted to integrate the functionality of this role into another role, how would I do so? Would it be enough to copy paste the tasks?

**Comment by thefinn93** [comment]
I haven't looked at the others. When I started this, I couldn't find anything that met my needs. Ansible has since included a [letsencrypt module](http://docs.ansible.com/ansible/letsencrypt_module.html), which would probably be a better idea to use.

**Comment by zfrenchee** [comment]
Okay, I will use the letsencrypt module instead. I guess my last question then is: are there any reasons to use this package instead of the module?

**Comment by thefinn93** [comment]
I dunno. I actually just noticed that module last week and am planning to look at it more throughly and update the README of this repo to point to it.

**Comment by zfrenchee** [comment]
@thefinn93 let me know how this goes. I'm personally really intereseted -- and strangely I don't see any roles/playbooks on the ansible galaxy that use this new letsencrypt module. I'd love to hear more about this from someone who knows how this works!
