### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by sobolevn** [thefinn93/ansible-letsencrypt#54]
Thanks for this project. It is perfectly working and is very helpful. But `README.md` states that:

> `letsencrypt_server` sets the auth server. Set to `https://acme-staging.api.letsencrypt.org/directory` to use the staging server (far higher rate limits, but certs are not trusted, intended for testing)

But in `default.yml` there's nothing about it. It is only possible to configure that var to add `--server` param to `letsecrypt`. 

If that's fine I'll send a PR with the fix.

**Comment by thefinn93** [comment]
wow, my bad! I I believe what the README says was true at one point, but was changed when Let's Encrypt went public and I forgot to update the README. A PR would be much appriciated
